### ISSUE TITLE
Classified 

### ISSUE THREAD

**Issue by Muhammad-Tanveer** [morethanoneanimal/Nagel-Schreckenberg-simulation#1]
How to define the heterogeneous traffic on MATLAB CODE. 

how can i specify the array for car, bus, etc ..... in one code

**Comment by shanto268** [comment]
> How to define the heterogeneous traffic on MATLAB CODE.
> 
> how can i specify the array for car, bus, etc ..... in one code
 I am facing the same problem. Did you figure it out? If so please share.

**Comment by morethanoneanimal** [comment]
I know I'm late to the party, but what do you mean matlab code? It's probably too late anyway, so I'm declaring bankruptcy!
